In [271]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
from madam import Madam
from matplotlib import pyplot as plt
%matplotlib inline

In [272]:
torch.random.manual_seed(1)
np.random.seed(1)
n = 5
w = torch.rand(n)
x = torch.rand(n)
print(w)
class Loss(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x, mode):
        return torch.linalg.norm(x, mode)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])


In [273]:
class Net(nn.Module):
    def __init__(self, w):
        super(Net, self).__init__()
        self.w = nn.Parameter(w)

    def forward(self, x):
        return self.w - x

In [274]:
net = Net(w)
input_x = x
maxIter = 200
# optimizer = optim.Adam(net.parameters(), lr=0.01)
optimizer = Madam(net.parameters(), lr=0.01, p_scale=3.0, g_bound=10.0)
criterion = Loss()

In [275]:
test = True
for i in range(maxIter):
    print(i, net.w)
    output = net(input_x)
    if test:
        if i < 100:
            loss = criterion(output, 8)
        else:
            loss = criterion(output, float('inf'))
    else:
        loss = criterion(output, 8)
    net.zero_grad()
    loss.backward()
    optimizer.step()
    print(net.w.grad)
    if(loss.item()<1e-4):
        print(i)
        break
print(loss.item())

8627e-05, -9.8807e-01])
58 Parameter containing:
tensor([0.7849, 0.3329, 0.5298, 0.6506, 0.0539], requires_grad=True)
tensor([-1.3275e-10, -3.5828e-06, -2.2723e-02,  1.8168e-05, -9.8841e-01])
59 Parameter containing:
tensor([0.7850, 0.3332, 0.5309, 0.6502, 0.0544], requires_grad=True)
tensor([-1.2936e-10, -3.4917e-06, -2.2175e-02,  1.7728e-05, -9.8873e-01])
60 Parameter containing:
tensor([0.7850, 0.3335, 0.5321, 0.6498, 0.0550], requires_grad=True)
tensor([-1.2612e-10, -3.4046e-06, -2.1649e-02,  1.7309e-05, -9.8903e-01])
61 Parameter containing:
tensor([0.7851, 0.3338, 0.5331, 0.6494, 0.0556], requires_grad=True)
tensor([-1.2303e-10, -3.3213e-06, -2.1145e-02,  1.6907e-05, -9.8932e-01])
62 Parameter containing:
tensor([0.7852, 0.3342, 0.5342, 0.6490, 0.0562], requires_grad=True)
tensor([-1.2007e-10, -3.2417e-06, -2.0661e-02,  1.6523e-05, -9.8960e-01])
63 Parameter containing:
tensor([0.7853, 0.3345, 0.5353, 0.6486, 0.0567], requires_grad=True)
tensor([-1.1724e-10, -3.1654e-06, -2.0195e

In [266]:
print(x)
print(net.w)

tensor([0.7999, 0.3971, 0.7544, 0.5695, 0.4388])
Parameter containing:
tensor([0.7824, 0.3372, 0.5469, 0.6623, 0.2309], requires_grad=True)


In [85]:
tensor([0.4963, 0.6916, 0.6931, 0.2511, 0.4292])
tensor([0.4963, 0.6976, 0.6932, 0.2492, 0.4249])
tensor([0.5665, 0.6095, 0.8160, 0.3381, 0.5103])
tensor([0.6340, 0.4901, 0.8970, 0.4555, 0.6336])

tensor(0.8080, grad_fn=<CopyBackwards>)

In [133]:
print(x)

tensor([0.6341, 0.4901, 0.8964, 0.4556, 0.6323])
